"""
kkr_test_pipeline
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="python_1")
def python_1_func():
    print("Hello world!")

default_args={
    "owner": "kalyanreddy.kasireddy@astronomer.io,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-08-16", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "kalyanreddy.kasireddy@astronomer.io": "mailto:kalyanreddy.kasireddy@astronomer.io",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clilt7vco00a601kk5fz65ob1/cloud-ide/clkh90z4k004u01oa46rimwz4/clzwhqj780kzo01htivpuk81v",
    },
)
def kkr_test_pipeline():
    python_1 = python_1_func()

dag_obj = kkr_test_pipeline()
